[project]
name = "sst_dds_br"
description = "Registros simples de Saude e Seguranca do Trabalho para ERPNext/Frappe"
requires-python = ">=3.14,<3.15"
authors = [{ name = "GL SOLTEC", email = "dev@glsoltec.com.br" }]
readme = "README.md"
license = { file = "LICENSE" }
dynamic = ["version"]
dependencies = ["frappe>=16.0.0,<17.0.0"]

[build-system]
requires = ["flit_core>=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
erpnext = ">=16.0.0,<17.0.0"
hrms = ">=16.0.0,<17.0.0"
